#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Sep 26 16:41:07 2023

@author: arnaudlemaire
"""

## Code pour lire le fichier csv provenant de sortCAENdata.cpp  ##

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import csv
d=True

##  Importation du fichier

filepath='/home/nick/MSC/Plastic_scintillators/Compton_scattering_tests/Room_temperature_no_reflective_foil/plastic_woRF_2024_04_29/RAW/SDataR_plastic_woRF_sorted.csv'
df=pd.read_csv(f'{filepath}', delimiter= '\t' )

#filepath_fil='/Users/arnaudlemaire/ECL/Queens/Experiment/LS/ComptonNewDAQ/setup_2/80_50d/Setup2_UG_RF_1100V_80d_50d_240nsCoMPASS_1400_200lsb_15h/FILTERED/SDataF_Setup2_UG_RF_1100V_80d_50d_240nsCoMPASS_1400_200lsb_15h_COINSORTED.CSV'
#df_fil=pd.read_csv(f'{filepath_fil}', delimiter= '\t' )

##  Récupération des dataframes correspondant aux événements dans le liquide scintillant

df0=df[df['E0_AU']>0]
df2=df0[df0['E2_AU']>0]
df4=df0[df0['E4_AU']>0]

# df0_fil=df_fil[df_fil['E0_AU']>0]
# df2_fil=df0_fil[df0_fil['E2_AU']>0]
# df4_fil=df0_fil[df0_fil['E4_AU']>0]


### Liquide scintillateur en coincidence avec le canal 2 ou 4
#plt.hist(df2_fil['E0_AU'],histtype='step',density=d,label='Coincidence_with_ch2_50d_filtered', bins=100)
#plt.hist(df4_fil['E0_AU'],histtype='step',density=d,label='Coincidence_with_ch4_80d_filtered', bins=100)
#plt.hist(df0_fil['E0_AU'],label="Total_LSC_fil",histtype='step', density =d, bins=100) #Comparaison avec le liquide scintillant sans coincidence
plt.hist(df2['E0_AU'],histtype='step',density=d,label='Coincidence_with_ch2_50d_raw', bins=120)
plt.hist(df4['E0_AU'],histtype='step',density=d,label='Coincidence_with_ch4_80_raw', bins=120)
plt.hist(df0['E0_AU'],label="Total_LSC_raw",histtype='step', density =d, bins=120) #Comparaison avec le liquide scintillant sans coincidence
#plt.yscale('log')
plt.xlim(0,800)
plt.ylim(0,0.004)
plt.title('LSC_Energy_Deposition_Coincidence')
plt.legend(loc='best',fontsize= 'small')
plt.xlabel('Energy_AU'); plt.ylabel('Counts_density')
plt.show()
plt.savefig('/Users/arnaudlemaire/ECL/Queens/Experiment/LS/ComptonNewDAQ/setup_2/80_50d/Setup2_UG_RF_1100V_80d_50d_240nsCoMPASS_1400_200lsb_15h/', dpi=400)
plt.clf()
